### ISSUE TITLE
Envelope support broken with refactor

### ISSUE THREAD

**Issue by mikesir87** [soulwing/prospecto#15]
Looks like support for envelope broke with the latest refactor.  Here's an example object and view template...

```java
  public class TestObject {
    private Long id;
    private Date startDate;
    private Date endDate;

    public Long getId() {
      return id;
    }
    public Date getStartDate() {
      return startDate;
    }

    public Date getEndDate() {
      return endDate;
    }

  }
```

and ViewTemplate:

```java
 ViewTemplate TEMPLATE = ViewTemplateBuilderProducer
      .object(TestObject.class)
        .value("id")
        .envelope("dates")
          .value("start").source("startDate")
          .value("end").source("endDate")
          .end()
        .build();
```

When the template is built, the following exception is thrown:

```
Caused by: org.soulwing.prospecto.api.ViewTemplateException: property 'dates' not found on type com.campstur.api.views.ViewMain$TestObject
	at org.soulwing.prospecto.runtime.accessor.ReflectionAccessorBuilder.build(ReflectionAccessorBuilder.java:88)
	at org.soulwing.prospecto.runtime.builder.AbstractViewTemplateBuilder.addChildToTarget(AbstractViewTemplateBuilder.java:434)
	at org.soulwing.prospecto.runtime.builder.AbstractViewTemplateBuilder.value(AbstractViewTemplateBuilder.java:117)
	at org.soulwing.prospecto.runtime.builder.AbstractViewTemplateBuilder.value(AbstractViewTemplateBuilder.java:111)
	at com.campstur.api.views.ViewMain.<clinit>(ViewMain.java:35)
```

where line 35 of ViewMain equates to the same line as ```.value("start").source("startDate")```

**Comment by ceharris** [comment]
Fixed in 99c84c6
