### ISSUE TITLE
NPE when updating with envelope

### ISSUE THREAD

**Issue by mikesir87** [soulwing/prospecto#17]
An NPE is being thrown when calling update on a view that makes use of an envelope.  If I remove the envelope from the view and update the json, it does work as expected.

### Entity

```java
public static class TestObject {
  private Date startDate;
  private Date endDate;

  public Date getStartDate() {
    return startDate;
  }

  public void setStartDate(Date startDate) {
    this.startDate = startDate;
  }

  public Date getEndDate() {
    return endDate;
  }

  public void setEndDate(Date endDate) {
    this.endDate = endDate;
  }
}
```

### Template

```java
static ViewTemplate TEMPLATE = ViewTemplateBuilderProducer
    .object(TestObject.class)
      .envelope("dates")
        .value("start").source("startDate")
        .value("end").source("endDate")
        .end()
      .build();
```

### Model updating

```java
    TestObject test = new TestObject();
    test.endDate = new Date(20000L);
    test.startDate = new Date(50000L);

    String json = "{\"dates\":{\"start\":70000,\"end\":80000}}";
    ViewReaderFactory readerFactory = ViewReaderFactoryProducer
        .getFactory("JSON", Collections.<String, Object>emptyMap());

    ViewReader reader = readerFactory.newReader(
        new ByteArrayInputStream(json.getBytes()));
    View updateView = reader.readView();


    ModelEditor editor = TEMPLATE.generateEditor(updateView,
        ViewContextProducer.newContext());

    editor.update(test);
```

### Exception

```
Caused by: java.lang.NullPointerException
	at org.soulwing.prospecto.runtime.node.ObjectNode.getModelObject(ObjectNode.java:101)
	at org.soulwing.prospecto.runtime.node.ObjectNode.inject(ObjectNode.java:71)
	at org.soulwing.prospecto.runtime.entity.ConcreteMutableViewEntity.inject(ConcreteMutableViewEntity.java:107)
	at org.soulwing.prospecto.runtime.node.RootObjectNode.update(RootObjectNode.java:85)
	at org.soulwing.prospecto.runtime.editor.ConcreteModelEditor.update(ConcreteModelEditor.java:73)
	... 6 more
```

**Comment by ceharris** [comment]
fixed by 9586093
