### ISSUE TITLE
Exception when creating ViewTemplate in which property is defined on parent interface

### ISSUE THREAD

**Issue by mikesir87** [soulwing/prospecto#46]
Classes and template definitions...

```java
public interface Persistable {
    Long getId();
    // Other stuff here
}

public interface Approver {
    Person getAuthority();
    // Other stuff here
}

public interface ApproverView {
    ViewTemplate DETAIL = ViewTemplateBuilderProducer
        .object(Approver.class)
          .url()
          .value("id")
          .reference("authority", PersonView.SUMMARY)
          .build();
}
```

When the template is created, I get the following exception...

```
Caused by: org.soulwing.prospecto.api.ViewTemplateException: property 'id' not found on type Approver
	at org.soulwing.prospecto.runtime.accessor.ReflectionAccessorBuilder.build(ReflectionAccessorBuilder.java:72)
	at org.soulwing.prospecto.runtime.builder.AbstractViewTemplateBuilder.injectAccessor(AbstractViewTemplateBuilder.java:563)
	at org.soulwing.prospecto.runtime.builder.AbstractViewTemplateBuilder.addChildToTarget(AbstractViewTemplateBuilder.java:555)
	at org.soulwing.prospecto.runtime.builder.AbstractViewTemplateBuilder.value(AbstractViewTemplateBuilder.java:121)
	at org.soulwing.prospecto.runtime.builder.AbstractViewTemplateBuilder.value(AbstractViewTemplateBuilder.java:115)
	at ApproverView.<clinit>(ApproverView.java:36)
	... 31 more
```

**Comment by ceharris** [comment]
Interesting. Apparently the Bean Introspector doesn't see those properties even though there's a public accessor.

**Comment by ceharris** [comment]
This works:
```
public abstract class Persistable {
  public abstract Long getId();
}

public abstract class Activity extends Persistable {
}
```

But this does not:
```
public interface Persistable {
  Long getId();
}

public interface Activity {
}
```

**Comment by ceharris** [comment]
Looks like we'll have to use `Class.getInterfaces` to search the DAG.
